spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9091/file:~/.scavenger
    username: scavenger
    password: scavenger
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: false

scavenger:
  collector-server-url: http://localhost:8080
