spring:
  datasource:
    url: jdbc:h2:file:~/.scavenger;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: scavenger
    password: scavenger
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: false
  sql:
    init:
      continue-on-error: true
      schema-locations: classpath:/db/changelog/schema.sql
      mode: always
