name: Release
on:
  push:
    branches:
      - 'release/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build project
        run: ./gradlew assemble
      - name: Extract version
        run: echo "version=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_OUTPUT
        id: extract_version
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_ACTIONS_TOKEN }}
          tag_name: v${{ steps.extract_version.outputs.version }}
          files: |
            ./scavenger-agent-java/build/libs/scavenger-agent-java-${{ steps.extract_version.outputs.version }}.jar
            ./scavenger-old-agent-java/build/libs/scavenger-old-agent-java-${{ steps.extract_version.outputs.version }}.jar
            ./scavenger-api/build/libs/scavenger-api-boot-${{ steps.extract_version.outputs.version }}.jar
            ./scavenger-collector/build/libs/scavenger-collector-boot-${{ steps.extract_version.outputs.version }}.jar
          generate_release_notes: true
